const unitMap: Record<string, string> = {
  台: 'units',
  个: 'pcs',
  套: 'sets',
  件: 'pcs',
  条: 'pcs',
  箱: 'ctns',
  包: 'packs',
  桶: 'drums',
  卷: 'rolls',
  张: 'sheets',
  瓶: 'bottles',
  盒: 'boxes',
  袋: 'bags',
  根: 'pcs',
  只: 'pcs',
  双: 'pairs',
  组: 'sets',
  批: 'lots',
  吨: 'tons',
  '千克': 'kg',
  '公斤': 'kg',
  克: 'g',
  米: 'm',
  '厘米': 'cm',
  '毫米': 'mm',
  升: 'L',
  '毫升': 'mL',
  码: 'yds',
  '英尺': 'ft',
  '英寸': 'in',
  盘: 'rolls',
  扎: 'bundles',
  把: 'pcs',
  块: 'pcs',
  片: 'pcs',
  支: 'pcs',
  对: 'pairs',
  副: 'pairs',
  打: 'dozens',
  罐: 'cans',
  听: 'cans',
  册: 'volumes',
  辆: 'units',
  艘: 'units',
  架: 'units',
};

export function translateUnit(unit: string | null | undefined): string | null {
  if (!unit) return null;
  return unitMap[unit] || null;
}
